version: '3.0'

services:
  front:
    container_name: front
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm start
    restart: always