import {makeAutoObservable} from 'mobx'

export default class LotStore {
    constructor() {
        this._lots = [
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '1',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/2020_Audi_A3_S_Line_Edition_1_35_TD_2.0.jpg/4096px-2020_Audi_A3_S_Line_Edition_1_35_TD_2.0.jpg',
            userId: 1},
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '0',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Audi_Sport_Quattro_%283561163376%29.jpg',
            userId: 1},
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '1',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/1996AudiQuattroA4.jpg',
            userId: 1},
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '1',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/6/60/2009_Audi_R8_LMS_GT3_-_Flickr_-_exfordy.jpg',
            userId: 1},
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '1',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Audi_RS5_DTM_%28R17%29_of_Abt_Sportsline_%2810074810194%29.jpg',
            userId: 1},
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '1',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Mattias_Ekstr%C3%B6m_%28Audi_S1_EKS_RX_quattro%29_%2826862236195%29.jpg',
            userId: 1},
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '1',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Mattias_Ekstr%C3%B6m_%28Audi_S1_EKS_RX_quattro%29_%2826862236195%29.jpg',
            userId: 1},
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '1',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/2015_Audi_R18_E-Tron_Quattro_%2820423176112%29.jpg',
            userId: 1},
            {id: 1,
            end_at: '2022-09-29 12:24:28.096+05',
            approved: '1',
            body_style: 'Хэтчбек',
            brand: 'Audi',
            model: 'A3',
            engine_volume: 2100,
            power: 120,
            mileage: 65444,
            fuel: 'Бензин',
            drivetrain: 'Передний',
            transmission: 'Механическая',
            color: 'Красный',
            steering_wheel: 'Правый',
            description: 'Не бита, не крашена.',
            start_price: 30000,
            redemption_price: 200000,
            city: 'Тюмень',
            img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/2020_Audi_A3_S_Line_Edition_1_35_TD_2.0.jpg/4096px-2020_Audi_A3_S_Line_Edition_1_35_TD_2.0.jpg',
            userId: 1}
        ]
        this._bids = [
            {id: 1, userId: 1, lotId: 1, price: 40000}
        ]
        makeAutoObservable(this)
    }

    setLots(lots) {
        this._lots = lots;
    }

    setBids(bids) {
        this._bids = bids;
    }

    get lots() {
        return this._lots;
    }

    get bids() {
        return this._bids;
    }
}