export const ADMIN_ROUTE = '/admin'
export const LOT_ROUTE = '/lot'
export const SIGNUP_ROUTE = '/signup'
export const ADDLOT_ROUTE = '/addlot'
export const MYLOTS_ROUTE = '/mylots'
export const MYCHATS_ROUTE = '/mychats'
export const HOME_ROUTE = '/'